### PR TITLE
Fix issue#5

### LINKED ISSUE #5: Fabric version causes freeze on Preparing spawn area
I cloned the git repo and build the Fabric version with ./gradlew build and when I use the mod my Minecraft freezes on Preparing spawn area. When putting the mod on the server, nothing  happens, because the mixin is not injected. When I add the mixin to the server mixin "chickendropfeathersmod.mixins.json" The server freezes on Preparing spawn area as well.
This might be because of a conflict with another mod I have. I will test the mod without other mods now and try to figure out the problem.

### PR DESCRIPTION
**Pull request by d4rkm0nkey**
Fix issue #5 by removing the accessor and giving the EntityChickenMixin the same parent as EntityChicken.

### CODE REVIEW

**Comment by d4rkm0nkey** [comment]
Hope I did this correctly. This is my first pull request.

**Review by axelrindle — DISMISSED** [review]
I just checked out your modifications. While the game starts normally without problems, the `EntityGoalDropFeather` is not registered with new `ChickenEntity` anymore. In the current state this does not fix the linked issue.

By extending `AnimalEntity`, you technically create a new type of entity, [which is not how mixins work](https://fabricmc.net/wiki/tutorial:mixin_injects).

[As the FabricMC wiki states](https://fabricmc.net/wiki/tutorial:mixin_accessors), `Accessors` are the preferred way to access private fields, which the `goalSelector` is. My workaround was to use Reflection to get access to that field. The problem that needs to be addressed is the `NoSuchFieldException` that you encountered. That was initially the intention of the `MobEntityAccessor`, which did not work for an unknown reason.

**Comment by d4rkm0nkey** [comment]
I don't think you are right about this. I am not an expert in Fabric, but I learned that if you create a mixin to a class, you always want to have the same parent as the original class. The code like this worked for me, with old and new spawned chickens.
And I don't think there is a new type of Entity created.
In my opinion you used a workaround, while I used the straight forward way to do it.
But I will read into into mixins again and try to find out whether you are right about this or not.

**Comment by d4rkm0nkey** [comment]
The reason that the accessor did not work for me was because there is no getter method for the  goal selector. Instead the goalSelector was defined as protected.

**Comment by d4rkm0nkey** [comment]
I realized that the mixin documentation has changed a lot and that now accessors seem to have replaced the shadow annotation.
Your way of doing should have worked I guess, but I still don't really understand what is wrong about extending AnimalEntity.

**Comment by d4rkm0nkey** [comment]
For me it seems that you only use the interface to access values of classes that you don't want to inject.

**Comment by axelrindle** [comment]
By extending the `AnimalEntity` class, you use the `goalSelector` field of the mixin class and not that one from the `ChickenEntity`.

**Comment by d4rkm0nkey** [comment]
Are you sure about that? I will try to debug this.
Other mods are using the same technique like here:
https://github.com/Draylar/wolves-with-armor/blob/1.16/src/main/java/draylar/wolveswitharmor/mixin/WolfEntityMixin.java
although here they have a different approach to access the attributes I guess.

**Comment by axelrindle** [comment]
Extending the `ChickenEntity` class gave me the following error:

```
[20:47:04] [main/ERROR] (mixin) chickendropfeathersmod.mixins.json:EntityChickenMixin: Super class 'net.minecraft.entity.passive.ChickenEntity' of EntityChickenMixin was not found in the hierarchy of target class 'net/minecraft/entity/passive/ChickenEntity'
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: Super class 'net.minecraft.entity.passive.ChickenEntity' of EntityChickenMixin was not found in the hierarchy of target class 'net/minecraft/entity/passive/ChickenEntity'
	at org.spongepowered.asm.mixin.transformer.MixinInfo$SubType$Standard.validate(MixinInfo.java:590) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinInfo$State.validate(MixinInfo.java:326) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.validate(MixinInfo.java:904) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInitialise(MixinConfig.java:674) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:542) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:439) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:415) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:285) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) ~[fabric-loader-0.11.2.jar:0.9.2+mixin.0.8.2]
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157) ~[fabric-loader-0.11.2.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150) ~[fabric-loader-0.11.2.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_275]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_275]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_275]
	at net.fabricmc.loader.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:45) ~[fabric-loader-0.11.2.jar:?]
	at net.fabricmc.loader.EntrypointStorage$NewEntry.create(EntrypointStorage.java:112) ~[fabric-loader-0.11.2.jar:?]
	at net.fabricmc.loader.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:99) ~[fabric-loader-0.11.2.jar:?]
	at net.fabricmc.loader.EntrypointStorage.lambda$getEntrypointContainers$1(EntrypointStorage.java:184) ~[fabric-loader-0.11.2.jar:?]
	at net.fabricmc.loader.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:37) [fabric-loader-0.11.2.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50) [fabric-loader-0.11.2.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36) [fabric-loader-0.11.2.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:137) [fabric-loader-0.11.2.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.2.jar:?]
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) [dev-launch-injector-0.2.1+build.8.jar:?]
```

**Comment by d4rkm0nkey** [comment]
This error makes sense, because ChickenEntity is not a parent class of ChickenEntity. Instead you need to extend the actual parent class of ChickenEntity, which is AnimalEntity.

**Comment by d4rkm0nkey** [comment]
I think mixin will not create a ChickenEntityMixin class, but instead will insert the code lines into the ChickenEntity class, so on runtime there is no ChickenEntityMixin object, but only ChickenEntity objects and they don't have two goalSelectors.
Extending a class in a mixin is only for being able to compile it I think, but I am not sure though.

**Comment by axelrindle** [comment]
I don't know why, but suddenly it started working. Strange...

**Comment by d4rkm0nkey** [comment]
What exactly wasn't working at the beginning? Did chicken not drop feathers? 
First I thought it doesn't work as well, when I lowered the number of ticks until the next feather, but then I realized that you write the number until the next feather into the tags, which is nice, but I had to wait until the feathers started to drop faster.
The mod works for me like this and I learned to write mixins like that, however I don't know if this is the correct or "best practice" way of doing it. You can test it more or look into the docs or other mods more, if you want to find out if this is a good way of doing it. I think it works.
I like that you have a very professional way of doing things and I will try to learn from that.
If you think that adding a settings menu for users to change the drop rate of feathers would be a good idea, I can make a feature-request, pull request and implement that with cloth config as well. Just tell me.

**Comment by axelrindle** [comment]
I don't think adding an option to change the drop rate would be very realistic, as I'm pretty sure that would be abused.

**Comment by d4rkm0nkey** [comment]
Yeah you could be right. Such an option should only be working on Singleplayer or must be defined by the server, which makes things complicative and people in SP would probably increase the rate, whenever they need feathers.

**Pull request merged**
